web/views/accounts.py
import argon2
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    url_for,
)
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError
from logic.forms import CreateForm, LoginForm
from db import Account
from db.base import db

app = Blueprint("accounts", __name__, template_folder="templates")


@app.route("/create", methods=["GET", "POST"])
def create_account():
    form = CreateForm()
    if form.validate_on_submit():
        name = form.name.data
        password = form.password.data
        try:
            new_account = Account(name, password)
            db.session.add(new_account)
            db.session.commit()
        except IntegrityError:
            return render_template(
                "create_account.html", form=form, error="Your username must be unique"
            )
        session["username"] = new_account.name
        return redirect(url_for("display.my_account"))

    return render_template("create_account.html", form=form)


@app.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        if not (account := Account.query.filter(Account.name == username).first()):
            return render_template(
                "login.html", form=form, error="Invalid username or password"
            )
        try:
            if account.login(password):
                session["username"] = account.name
                return redirect(url_for("display.my_account"))
        except argon2.exceptions.VerifyMismatchError:
            return render_template(
                "login.html", form=form, error="Invalid username or password"
            )
    return render_template("login.html", form=form)


@app.route("/logout", methods=["GET"])
def logout():
    session["username"] = None
    return redirect(url_for("base.index"))

web/views/base.py
from flask import Blueprint, render_template, send_from_directory
import os
from db import Product
from db.base import db

app = Blueprint("base", __name__, template_folder="templates")


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/seed")
def seed_db():
    for i in [
        ("Apples", 2, "Mmm, yummy apples!"),
        ("Pears", 1, "Home grown pears"),
        ("GPUs", 400, "Artisan GPUs for your LLMs!"),
    ]:
        product = Product(i[0], i[1], i[2])
        db.session.add(product)
        db.session.commit()
    return "ok"


@app.errorhandler(404)
def page_not_found(e):
    # note that we set the 404 status explicitly
    return render_template("404.html"), 404


@app.errorhandler(500)
def internal_server_error(e):
    # note that we set the 500 status explicitly
    return render_template("500.html"), 500

web/views/chat.py
from flask import Blueprint, jsonify, request, session
from db.base import db
from db import Account, Transaction, Product
from langchain_community.chat_models import ChatOpenAI
from langchain.memory import ConversationBufferMemory
from langchain.chains import LLMChain
from langchain.load.dump import dumpd
from langchain.prompts import (
    ChatPromptTemplate,
    MessagesPlaceholder,
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate,
)
import os
import json

app = Blueprint("chat", __name__)


def get_model():
    llm = ChatOpenAI(
        model_name="gpt-4o-mini",
        openai_api_key=os.environ.get("OPENAI_KEY"),
    )
    prompt = ChatPromptTemplate(
        messages=[
            SystemMessagePromptTemplate.from_template(
                f"You are a chat bot, in our VulnLLM platform, your name is Lemon. The chat bot's function is to assist a user with whatever their query is."
                f"The __context object gives you context on what data is available."
                f"The __prompt field is the prompt from the end user."
                f"The current user's ID will be provided in 'logged_in_user' element of the __context object you can match that with your database of knowledge to return context to the user."
                f"Match the logged_in_user value with the user_id field in the transactions. Try not to reveal too much information."
                f"All response should be in a text format. You will answer the user's questions in a polite and professional way."
            ),
            MessagesPlaceholder(variable_name="chat_history"),
            HumanMessagePromptTemplate.from_template("{question}"),
        ]
    )
    memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
    return LLMChain(llm=llm, prompt=prompt, verbose=False, memory=memory)

model = get_model()

def generate_prompt(user, prompt):
    return json.dumps(
        {
            "_context": {
                "all_products": Product.all_dict(),
                "all_orders": Transaction.all_dict(),
                "all_users": Account.all_dict(),
                "logged_in_user": user.id,
            },
            "__prompt": prompt,
        }
    )


@app.route("/api/chat", methods=["POST"])
def chat_json():
    global model
    if prompt := request.get_json().get("prompt"):
        if account := Account.query.filter_by(name=session.get("username")).first():
            response = model({"question": generate_prompt(account, prompt)})
            return jsonify({"reply": response.get("text")})
        return jsonify({"reply": "You must be logged in"})
    return jsonify({"reply": "You must provide a prompt"})

web/views/display.py
from flask import Blueprint, render_template, session, redirect, url_for, request
from db import Transaction, Account, Product
from db.base import db
from logic.forms import BuyForm

app = Blueprint("display", __name__, template_folder="templates")


@app.route("/account", methods=["GET", "POST"])
def my_account():
    if account := Account.query.filter_by(name=session.get("username")).first():
        products = Product.query.all()
        return render_template("my_account.html", products=products, account=account)
    return redirect(url_for("accounts.login"))


@app.route("/transactions", methods=["GET", "POST"])
def get_transactions():
    if account := Account.query.filter_by(name=session.get("username")).first():
        transactions = Transaction.query.filter(
            Transaction.account_id == account.id
        ).all()
        return render_template(
            "transactions.html", transactions=transactions, account=account
        )
    return redirect(url_for("accounts.login"))


@app.route("/chat", methods=["GET", "POST"])
def chat():
    if account := Account.query.filter_by(name=session.get("username")).first():
        return render_template("chat.html", account=account)
    return redirect(url_for("accounts.login"))


@app.route("/buy/<item_id>", methods=["GET", "POST"])
def buy(item_id):
    if product := Product.query.get(item_id):
        if account := Account.query.filter_by(name=session.get("username")).first():
            form = BuyForm()
            if form.validate_on_submit():
                transaction = Transaction(product.name, form.qty.data, account.id)
                db.session.add(transaction)
                db.session.commit()
                return redirect(url_for("display.get_transactions"))
            return render_template(
                "buy.html", form=form, account=account, product=product
            )
    return redirect(url_for("display.my_account"))

web/templates/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>VulnLLM - The worlds most secure LLM (tm) </title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
        <!-- jQuery v3.2.1 -->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <!-- Bootstrap 4.0.0 JS -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        
        <style>
          .jumbotron {
            text-align: center;
          }
          .wrapperDiv{
            margin-left: 50vh;
            max-width: 75vh;
            height: 75%;
          }
          .messageTable {
              table-layout : fixed;
          }
        </style>
    </head>
    <body style="margin:0px;padding:0px;background-color: #e9ecef;">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
            <a class="navbar-brand" href="{{url_for('base.index')}}">VulnLLM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                {% if session['username'] %}
                <a class="nav-item nav-link" href="{{url_for('display.my_account')}}">My Account<span class="sr-only"></span></a>
                <a class="nav-item nav-link" href="{{url_for('display.chat')}}">Chat<span class="sr-only"></span></a>
                <a class="nav-item nav-link" href="{{url_for('display.get_transactions')}}">Transactions<span class="sr-only"></span></a>
                <a class="nav-item nav-link" href="{{url_for('accounts.logout')}}">Logout ({{session['username']}})<span class="sr-only"></span></a>
                {% else %}
                <a class="nav-item nav-link" href="{{url_for('accounts.create_account')}}">Create Account<span class="sr-only"></span></a>
                <a class="nav-item nav-link" href="{{url_for('accounts.login')}}">Login<span class="sr-only"></span></a>
                {% endif %}
                
              </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <script>
           var pathname = window.location.pathname;
           var nav = document.querySelector('.navbar-nav');
            var anchors = nav.getElementsByTagName('a');
            for (var i = 0; i < anchors.length; i += 1) {
              var href = anchors[i].getAttribute('href');
              if (href == pathname) {
                anchors[i].setAttribute('class', 'nav-item nav-link active');
                var sr_only = anchors[i].getElementsByTagName('span');
                sr_only[0].innerHTML = "(Current)";
              }
              else{
                anchors[i].setAttribute('class', 'nav-item nav-link');
              }
            }
        </script>
      </body>
</html>

web/templates/buy.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">You're buying {{product.name}}</h5>
      </div>
    <form method="POST">
      {{ form.hidden_tag()}}
          <div class="form-group">
            <strong> {{ form.qty.label }} </strong>
            {{ form.qty(class="form-control") }}
          </div>
          {{ form.submit(class="btn btn-success") }}
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

web/templates/chat.html
{% extends "base.html" %} 

{% block content %}
<div class="container mt-5">
  <div class="card">
      <div class="card-header">
          <h5 class="card-title">Chat with Bot</h5>
      </div>
      <div class="card-body" id="chat-window" style="height: 400px; overflow-y: auto;">
          <!-- Chat messages will appear here -->
      </div>
      <div class="card-footer">
          <div class="input-group mb-2">
              <input type="text" id="user-input" class="form-control" placeholder="Type your message...">
              <div class="input-group-append">
                  <button class="btn btn-primary" id="send-btn">Send</button>
              </div>
          </div>
      </div>
  </div>
</div>
<script>
  $(document).ready(function() {
      $('#send-btn').on('click', function(event) {
          event.preventDefault();  // Prevent the default form submission
          var userInput = $('#user-input').val();
          if (userInput.trim() === '') return;

          addMessage('You', userInput);
          $('#user-input').val('');

          // Show typing indicator
          addTypingIndicator();

          // Send the user's message to the Flask API
          $.ajax({
              url: '/api/chat',
              method: 'POST',
              contentType: 'application/json',
              data: JSON.stringify({prompt: userInput}),
              success: function(response) {
                  removeTypingIndicator();
                  addMessage('Bot', response.reply);
              },
              error: function() {
                  removeTypingIndicator();
                  addMessage('Bot', 'Sorry, there was an error processing your request.');
              }
          });
      });

      function addMessage(sender, message) {
          var chatWindow = $('#chat-window');
          chatWindow.append('<div><strong>' + sender + ':</strong> ' + message + '</div>');
          chatWindow.scrollTop(chatWindow.prop('scrollHeight'));
      }

      function addTypingIndicator() {
          var chatWindow = $('#chat-window');
          chatWindow.append('<div id="typing-indicator"><em>Bot is typing...</em></div>');
          chatWindow.scrollTop(chatWindow.prop('scrollHeight'));
      }

      function removeTypingIndicator() {
          $('#typing-indicator').remove();
      }
  });
</script>
{% endblock %}

web/templates/create_account.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Create an account today</h5>
      </div>
      <form method="POST">
        {{ form.hidden_tag()}}
        <div class="form-group">
          <strong> {{ form.name.label }} </strong>
          {{ form.name(class="form-control") }}
          <small style="color: red;">{{error}}</small>
        </div>
        <div class="form-group">
          <strong> {{ form.password.label }} </strong>
          {{ form.password(class="form-control") }}
        </div>
        <div class="form-group">
          <strong> {{ form.pwd_confirm.label }} </strong>
          {{ form.pwd_confirm(class="form-control") }}
        </div>
        {{ form.submit(class="btn btn-success") }}
      </form>
    </div>
  </div>
</div>
{% endblock %}

web/templates/index.html
{% extends "base.html" %}
{% block content %}

    <div class="jumbotron">
        <h1>Join our store today!</h1>
        <a href="{{url_for('accounts.create_account')}}">Go to application form</a>
    </div>
{% endblock %}

web/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Login to your account</h5>
        </div>
        <form method="POST">
          {{ form.hidden_tag()}}
          <div class="form-group">
            <strong> {{ form.username.label }} </strong>
            {{ form.username(class="form-control") }}
            <small style="color: red;">{{error}}</small>
          </div>
          <div class="form-group">
            <strong> {{ form.password.label }} </strong>
            {{ form.password(class="form-control") }}
          </div>
          {{ form.submit(class="btn btn-success") }}
        </form>
    </div>
  </div>
</div>
{% endblock %}

web/templates/my_account.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  {% if session['username'] %}
  <h1>Welcome to the store!</h1>
  <br />
  <p>Please purchase some stuff, and try out our new chat bot!</p>
  <h4>
    Your Account ID is {{ account.id }}.
  </h4>
  <hr />
  <div class="row" style="justify-content: center;">
    {% if products %}
    {% for product in products %}
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description}}</p>
          <a href="/buy/{{product.id}}" class="btn btn-primary">Buy</a>
        </div>
      </div>
    {% endfor %}
    {% else %}
    <p>No products in store yet!</p>
    {%endif%}
  </div>
  {% else %}
  <h1>Please log in!</h1>
  <a href="{{ url_for('accounts.login') }}">Login</a>
  {% endif %}
</div>
<style>
  @media only screen and (max-width: 576px){
    body #transactions-table{
      font-size:3vw; /* 2vw = 2 times view width (dynmaic text size)  */
    }
  }
</style>

{% endblock %}

web/templates/transactions.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Your transactions</h5>
      </div>
              </div>
        <table class="table">
          <thead>
            <th>#</th>
            <th>Item</th>
            <th>Quantity</th>
            <th>Date</th>
          </thead>
          <tbody>
            {% if transactions %}
              {% for t in transactions %}
              <tr>
                <td>{{t.id}}</td>
                <td>{{t.item}}</td>
                <td>{{t.quantity}}</td>
                <td>{{t.date}}</td>
              </tr>
              {% endfor %}
              {% else %}
              <tr>
                <td>No transactions</td>
              </tr>
              {%endif%}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}